### ISSUE TITLE
There is no Copy libDynamsoftBarcodeReader.so/libDynamsoftBarcodeReader.dylib in sdk or else where

### ISSUE THREAD

**Issue by ajithvallabai** [dynamsoft-dbr/python-barcode#6]
I want to use dbr along with python could you please give me instructions

**Comment by yushulx** [comment]
@ajithvallabai linux: https://github.com/dynamsoft-dbr/python-barcode/releases/download/v7.2.2/dbr-linux-7.2.2.tar.gz. mac: https://github.com/dynamsoft-dbr/python-barcode/releases/download/v7.2.2/dbr-mac-7.2.2.zip

**Comment by yushulx** [comment]
@ajithvallabai how to build: https://github.com/dynamsoft-dbr/python-barcode/blob/master/src/README.md

**Comment by ajithvallabai** [comment]
Thanks @yushulx
